### ISSUE TITLE
Running rspec tests. `require 'rvm'` fails

### ISSUE THREAD

**Issue by juliancooper** [sous-chefs/chef-rvm#254]
I'm developing a cookbook that requires chef. It seems like `require 'rvm'` is causing the tests to fail. I've tried stubbing out `Kernel.require` unsuccessfully. Spec code to follow after log output. 

```
================================================================================
Recipe Compile Error in chef-repo/cookbooks/<my_cookbook>/recipes/default.rb
================================================================================

LoadError
---------
cannot load such file -- rvm

Cookbook Trace:
---------------
  chef-repo/cookbooks/rvm/recipes/default.rb:27:in `require'
  chef-repo/cookbooks/rvm/recipes/default.rb:27:in `from_file'
  chef-repo/cookbooks/rvm/recipes/system_install.rb:20:in `from_file'
  chef-repo/cookbooks/rvm/recipes/system.rb:20:in `from_file'
  chef-repo/cookbooks/<my_cookbook>/recipes/default.rb:13:in `from_file'
  chef-repo/cookbooks/<my_cookbook>/spec/recipes/default_spec.rb:8:in `block (2 levels) in <top (required)>'

Relevant File Content:
----------------------
chef-repo/cookbooks/rvm/recipes/default.rb:

 20:  # install rvm api gem during chef compile phase
 21:  gem_package 'rvm' do
 22:    action :nothing
 23:  end.run_action(:install)
 24:
 25:  require 'rubygems'
 26:  Gem.clear_paths
 27>> require 'rvm'
 28:  create_rvm_shell_chef_wrapper
 29:  create_rvm_chef_user_environment
 30:
 31:  class Chef::Resource
 32:    # mix in #rvm_cmd_wrap helper into resources
 33:    include Chef::RVM::ShellHelpers
 34:  end
 35:
 36:  class Chef::Recipe

F
```

default_spec.rb

``` ruby
require_relative '../spec_helper'

describe '<my_cookbook>::default' do
  # let(:chef_run) { ChefSpec::Runner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe)}

  before(:each) do 
    Kernel.stub(:require).with('rvm')
    chef_run = ChefSpec::Runner.new(platform: 'ubuntu', version: '12.04').converge(described_recipe)
  end
  # Write quick specs using `it` blocks with implied subjects
  it 'installs rvm system-wide' do
    expect(chef_run).to include_recipe 'rvm::system'
  end

  # ...
end
```

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
