### ISSUE TITLE
cannot load such file -- chef/application/solo

### ISSUE THREAD

**Issue by MarkMurphy** [sous-chefs/chef-rvm#264]
```
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default: : 
==> default: cannot load such file -- chef/application/solo
==> default:  (
==> default: LoadError
==> default: )
==> default:    from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default:    from /usr/bin/chef-solo:22:in `<main>'
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

See https://gist.github.com/icambron/5556420

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
