### ISSUE TITLE
can't install rvm for user 

### ISSUE THREAD

**Issue by burdandrei** [sous-chefs/chef-rvm#269]
Hi, we're trying to run rvm in AWS OpsWorks environment.
System wide ruby is installing ok, but then there is an issue with gemset, because all /usr/local/rvm folder is owned by root:rvm , but folders of rubies itself are root:root, so even if my application user is in rvm group he can't initialise gemset or do bundle install,  that is bug by itself, i think.

So i tried to install rvm for this user only, and unfortunately here's what i received:

```
[2014-09-03T07:59:13+00:00] INFO: Processing chef_gem[rvm] action install (rvm::default line 21)
[2014-09-03T07:59:13+00:00] INFO: Processing package[sed] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[grep] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[tar] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[gzip] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[bzip2] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[bash] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[curl] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing package[git-core] action install (rvm::user_install line 45)
[2014-09-03T07:59:13+00:00] INFO: Processing template[/home/deploy/.rvmrc] action create (rvm::user_install line 145)
[2014-09-03T07:59:13+00:00] INFO: template[/home/deploy/.rvmrc] created file /home/deploy/.rvmrc
[2014-09-03T07:59:13+00:00] INFO: template[/home/deploy/.rvmrc] updated file contents /home/deploy/.rvmrc
[2014-09-03T07:59:13+00:00] INFO: template[/home/deploy/.rvmrc] owner changed to 4000
[2014-09-03T07:59:13+00:00] INFO: template[/home/deploy/.rvmrc] mode changed to 644
[2014-09-03T07:59:13+00:00] INFO: Processing execute[install user RVM for deploy] action run (rvm::user_install line 76)
[2014-09-03T07:59:16+00:00] INFO: execute[install user RVM for deploy] ran successfully
[2014-09-03T07:59:16+00:00] INFO: Processing execute[upgrade user RVM for deploy to none] action run (rvm::user_install line 115)
[2014-09-03T07:59:16+00:00] INFO: Processing rvm_default_ruby[ruby-1.9.3-p327] action create (rvm::user line 185)

================================================================================
Error executing action `create` on resource 'rvm_default_ruby[ruby-1.9.3-p327]'
================================================================================


RVM::IncompleteCommandError
---------------------------
RVM::IncompleteCommandError


Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:45:in `block in run_command'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:72:in `with_shell_instance'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/rvm_shell_chef_wrapper.rb:39:in `run_command'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:59:in `current_ruby_default'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/chef_rvm_ruby_helpers.rb:68:in `ruby_default?'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/providers/default_ruby.rb:56:in `skip_ruby?'
/var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/providers/default_ruby.rb:33:in `block in class_from_file'


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb

185:         rvm_default_ruby opts[:default_ruby] do
186:           user  opts[:user]
187:         end
188: 



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:185:in `install_rubies'

rvm_default_ruby("ruby-1.9.3-p327") do
action :create
retries 0
retry_delay 2
cookbook_name "rvm"
recipe_name "user"
user "deploy"
ruby_string "ruby-1.9.3-p327"
end



[2014-09-03T07:59:18+00:00] INFO: Running queued delayed notifications before re-raising exception
[2014-09-03T07:59:18+00:00] ERROR: Running exception handlers
[2014-09-03T07:59:18+00:00] ERROR: Exception handlers complete
[2014-09-03T07:59:18+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2014-09-03T07:59:18+00:00] ERROR: rvm_default_ruby[ruby-1.9.3-p327] (rvm::user line 185) had an error: RVM::IncompleteCommandError: RVM::IncompleteCommandError
[2014-09-03T07:59:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Any suggestions?

**Comment by docwhat** [comment]
I was able to work around this by switching to cookbook version eddd733 -- Maybe what's out should be released?

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
