### ISSUE TITLE
Chef::Exceptions::ImmutableAttributeModification

### ISSUE THREAD

**Issue by heaven** [sous-chefs/chef-rvm#272]
This code:

``` ruby
node_val = node['rvm']['gem_package']['rvm_string']
case node_val
when String
  rvm_descriptor = node_val + " RVM Ruby"
when Array
  last = node_val.pop
  rvm_descriptor = [ node_val.join(', '), last ].join(' & ') + " RVM Rubies"
end
```

Rises:

```
Chef::Exceptions::ImmutableAttributeModification: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/node/immutable_collections.rb:82:in `pop'
/var/chef/cache/cookbooks/rvm/recipes/gem_package.rb:25:in `from_file'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/mixin/from_file.rb:30:in `from_file'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/cookbook_version.rb:237:in `load_recipe'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/run_context.rb:151:in `load_recipe'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/run_context.rb:86:in `load'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/client.rb:250:in `setup_run_context'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/client.rb:498:in `do_run'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/client.rb:199:in `block in run'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/client.rb:193:in `fork'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/client.rb:193:in `run'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/application.rb:208:in `run_chef_client'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/application/client.rb:312:in `block in run_application'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/application/client.rb:304:in `loop'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/application/client.rb:304:in `run_application'
/var/lib/gems/1.9.1/gems/chef-11.8.2/lib/chef/application.rb:66:in `run'
/var/lib/gems/1.9.1/gems/chef-11.8.2/bin/chef-client:26:in `<top (required)>'
/usr/local/bin/chef-client:19:in `load'
/usr/local/bin/chef-client:19:in `<main>'
```

You can't use pop here.

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
