### ISSUE TITLE
Ignoring node['rvm']['default_ruby']

### ISSUE THREAD

**Issue by llibicpep** [sous-chefs/chef-rvm#282]
I have the following attributes:

``` ruby
override['rvm']['default_ruby']      = "2.1"
override['rvm']['user_default_ruby'] = "2.1"
override['rvm']['rubies'] =  ['2.1']
```

And recipe:

``` ruby
...
include_recipe "rvm::system"
...
rvm_shell "gem install chef" do
  code %Q{gem install chef --no-rdoc --no-ri -v 11.14.6}
  timeout 36000
end
```

This machine bootstrapping via Vagrant.
During installing chef I'm getting the following:

```
==> knife-solo: ================================================================================
==> knife-solo: Error executing action `run` on resource 'script[gem install chef]'
==> knife-solo: ================================================================================
==> knife-solo: 
==> knife-solo: 
==> knife-solo: Mixlib::ShellOut::ShellCommandFailed
==> knife-solo: ------------------------------------
==> knife-solo: Expected process to exit with [0], but received '1'
==> knife-solo: ---- Begin output of "bash"  "/tmp/chef-script20141118-5776-1elfd1m" ----
==> knife-solo: STDOUT: Now using system ruby.
==> knife-solo: STDERR: ERROR:  Error installing chef:
==> knife-solo: 
==> knife-solo:     mime-types requires Ruby version >= 1.9.2.
==> knife-solo: ---- End output of "bash"  "/tmp/chef-script20141118-5776-1elfd1m" ----
==> knife-solo: Ran "bash"  "/tmp/chef-script20141118-5776-1elfd1m" returned 1
==> knife-solo: 
==> knife-solo: Cookbook Trace:
==> knife-solo: ---------------
==> knife-solo: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb:99:in `script_wrapper'
==> knife-solo: 
==> knife-solo: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb:46:in `block in class_from_file'
==> knife-solo: 
==> knife-solo: Resource Declaration:
==> knife-solo: ---------------------
==> knife-solo: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb
==> knife-solo: 
==> knife-solo:  76:   s = script new_resource.name do
==> knife-solo:  77:     interpreter   "bash"
==> knife-solo:  78: 
==> knife-solo:  79:     if new_resource.user
==> knife-solo:  80:       user        new_resource.user
==> knife-solo: 
==> knife-solo:  81:       if user_rvm && new_resource.environment
==> knife-solo:  82:         environment({ 'USER' => new_resource.user, 'HOME' => user_home }.merge(
==> knife-solo: 
==> knife-solo:  83:           new_resource.environment))
==> knife-solo: 
==> knife-solo:  84:       elsif user_rvm
==> knife-solo: 
==> knife-solo:  85:         environment({ 'USER' => new_resource.user, 'HOME' => user_home })
==> knife-solo:  86:       end
==> knife-solo:  87:     end
==> knife-solo: 
==> knife-solo: 
==> knife-solo: Compiled Resource:
==> knife-solo: ------------------
==> knife-solo: # Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb:76:in `script_wrapper'
==> knife-solo: 
==> knife-solo: 
==> knife-solo: 
==> knife-solo: script("gem install chef") do
==> knife-solo:   action [:nothing]
==> knife-solo:   retries 0
==> knife-solo:   retry_delay 2
==> knife-solo: 
==> knife-solo:   guard_interpreter :default
==> knife-solo:   command "\"bash\"  \"/tmp/chef-script20141118-5776-1elfd1m\""
==> knife-solo:   backup 5
==> knife-solo:   returns [0]
==> knife-solo:   timeout 36000
==> knife-solo:   code "    if [ -s \"${HOME}/.rvm/scripts/rvm\" ]; then\n      source \"${HOME}/.rvm/scripts/rvm\"\n    elif [ -s \"/etc/profile.d/rvm.sh\" ]; then\n      source \"/etc/profile.d/rvm.sh\"\n    fi\n\n    rvm use system\n\n    gem install chef --no-rdoc --no-ri -v 11.14.6\n"
==> knife-solo: 
==> knife-solo:   interpreter "bash"
==> knife-solo:   cookbook_name :"knife-solo"
==> knife-solo: 
==> knife-solo: end
==> knife-solo: 
==> knife-solo: 
==> knife-solo: 
==> knife-solo: 
==> knife-solo: ================================================================================
==> knife-solo: Error executing action `run` on resource 'rvm_shell[gem install chef]'
==> knife-solo: ================================================================================
==> knife-solo: 
==> knife-solo: 
==> knife-solo: Mixlib::ShellOut::ShellCommandFailed
==> knife-solo: ------------------------------------
==> knife-solo: script[gem install chef] (/tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb line 76) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> knife-solo: ---- Begin output of "bash"  "/tmp/chef-script20141118-5776-1elfd1m" ----
==> knife-solo: STDOUT: Now using system ruby.
==> knife-solo: STDERR: ERROR:  Error installing chef:
==> knife-solo:     mime-types requires Ruby version >= 1.9.2.
==> knife-solo: 
==> knife-solo: ---- End output of "bash"  "/tmp/chef-script20141118-5776-1elfd1m" ----
==> knife-solo: Ran "bash"  "/tmp/chef-script20141118-5776-1elfd1m" returned 1
==> knife-solo: 
==> knife-solo: 
==> knife-solo: Cookbook Trace:
==> knife-solo: ---------------
==> knife-solo: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb:99:in `script_wrapper'
==> knife-solo: 
==> knife-solo: /tmp/vagrant-chef-2/chef-solo-1/cookbooks/rvm/providers/shell.rb:46:in `block in class_from_file'
==> knife-solo: 
==> knife-solo: 
==> knife-solo: Resource Declaration:
==> knife-solo: ---------------------
==> knife-solo: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/knife-solo/recipes/default.rb
==> knife-solo: 
==> knife-solo: 
==> knife-solo: 
==> knife-solo:  40:     rvm_shell "gem install #{name}" do
==> knife-solo: 
==> knife-solo:  41:       code %Q{gem install #{name} --no-rdoc --no-ri -v #{version}}
==> knife-solo: 
==> knife-solo:  42:       timeout 36000
==> knife-solo: 
==> knife-solo:  43:     end
==> knife-solo: 
==> knife-solo:  44:   else
==> knife-solo: 
==> knife-solo: 
==> knife-solo: 
==> knife-solo: Compiled Resource:
==> knife-solo: ------------------
==> knife-solo: # Declared in /tmp/vagrant-chef-2/chef-solo-1/cookbooks/knife-solo/recipes/default.rb:40:in `block in from_file'
==> knife-solo: 
==> knife-solo: 
==> knife-solo: rvm_shell("gem install chef") do
==> knife-solo:   action :run
==> knife-solo:   retries 0
==> knife-solo: 
==> knife-solo:   retry_delay 2
==> knife-solo:   guard_interpreter :default
==> knife-solo:   cookbook_name :"knife-solo"
==> knife-solo:   recipe_name "default"
==> knife-solo:   code "gem install chef --no-rdoc --no-ri -v 11.14.6"
==> knife-solo: 
==> knife-solo:   timeout 36000
==> knife-solo: 
==> knife-solo:   ruby_string "default"
==> knife-solo: 
==> knife-solo:   returns [0]
==> knife-solo: 
==> knife-solo: end
==> knife-solo: 
==> knife-solo: 
==> knife-solo: 
```

When I ssh to this Vagrant box, I see that no ruby were installed with RVM. I've noticed on this line `==> knife-solo: STDOUT: Now using system ruby.`, so I've tried to add somewhere before `include_recipe "rvm::system"` removing OS wide installed ruby package. After that everything working as expected.
A month ago or so it was successful with the same Vagrant box.

Host OS Ubuntu 14.10, RVM 1.25.28, Ruby 2.1.2, Chef 11.14.6, Berkshelf 3.1.5
Vagrant is CentOS 6.5

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
