### ISSUE TITLE
RVM System install is broken

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sous-chefs/chef-rvm#306]
Trying to run `recipe[rvm::system]` on clean Ubuntu 14.04.1 LTS with Chef 11.18.0 (with quick fix for #307 ):

```
[2015-02-05T14:53:44+00:00] INFO: Processing remote_file[/home/ubuntu/chef/rvm-installer-root] action create (dynamically defined)
[2015-02-05T14:53:44+00:00] INFO: remote_file[/home/ubuntu/chef/rvm-installer-root] created file /home/ubuntu/chef/rvm-installer-root
[2015-02-05T14:53:44+00:00] INFO: remote_file[/home/ubuntu/chef/rvm-installer-root] updated file contents /home/ubuntu/chef/rvm-installer-root

================================================================================
Error executing action `install` on resource 'rvm_installation[root]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '2'
---- Begin output of bash /home/ubuntu/chef/rvm-installer-root stable ----
STDOUT: Downloading https://github.com/wayneeseguin/rvm/archive/1.26.10.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.10.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc'!
try downloading the signatures:

    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
STDERR: gpg: Signature made Mon Feb  2 16:09:00 2015 UTC using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
---- End output of bash /home/ubuntu/chef/rvm-installer-root stable ----
Ran bash /home/ubuntu/chef/rvm-installer-root stable returned 2

Cookbook Trace:
---------------
/home/ubuntu/chef/site-cookbooks/rvm/libraries/provider_rvm_installation.rb:156:in `rvm_shell_out!'
/home/ubuntu/chef/site-cookbooks/rvm/libraries/provider_rvm_installation.rb:107:in `run_install_cmd'
/home/ubuntu/chef/site-cookbooks/rvm/libraries/provider_rvm_installation.rb:70:in `install_rvm'
/home/ubuntu/chef/site-cookbooks/rvm/libraries/provider_rvm_installation.rb:63:in `block in converge_install'
/home/ubuntu/chef/site-cookbooks/rvm/libraries/provider_rvm_installation.rb:63:in `converge_install'
/home/ubuntu/chef/site-cookbooks/rvm/libraries/provider_rvm_installation.rb:50:in `action_install'

Resource Declaration:
---------------------
# In /home/ubuntu/chef/site-cookbooks/rvm/recipes/system_install.rb

 42: rvm_installation("root")

Compiled Resource:
------------------
# Declared in /home/ubuntu/chef/site-cookbooks/rvm/recipes/system_install.rb:42:in `from_file'

rvm_installation("root") do
  provider Chef::Provider::RvmInstallation
  action :install
  retries 0
  retry_delay 2
  guard_interpreter :default
  user "root"
  installer_url "https://get.rvm.io"
  installer_flags "stable"
  install_pkgs ["sed", "grep", "tar", "gzip", "bzip2", "bash", "curl", "git-core"]
  rvmrc_template_source "rvmrc.erb"
  rvmrc_template_cookbook "rvm"
  default_rvmrc_env {"rvm_gem_options"=>"--no-ri --no-rdoc"}
  rvmrc_env {"rvm_gem_options"=>"--no-ri --no-rdoc"}
  cookbook_name :rvm
  recipe_name "system_install"
end

[2015-02-05T14:53:47+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-02-05T14:53:47+00:00] ERROR: Running exception handlers
[2015-02-05T14:53:47+00:00] ERROR: Exception handlers complete
[2015-02-05T14:53:47+00:00] FATAL: Stacktrace dumped to /home/ubuntu/chef/chef-stacktrace.out
[2015-02-05T14:53:47+00:00] ERROR: rvm_installation[root] (rvm::system_install line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of bash /home/ubuntu/chef/rvm-installer-root stable ----
STDOUT: Downloading https://github.com/wayneeseguin/rvm/archive/1.26.10.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.10.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc'!
try downloading the signatures:

    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
STDERR: gpg: Signature made Mon Feb  2 16:09:00 2015 UTC using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
---- End output of bash /home/ubuntu/chef/rvm-installer-root stable ----
Ran bash /home/ubuntu/chef/rvm-installer-root stable returned 2
[2015-02-05T14:53:47+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by krukgit** [comment]
I have the exact same problem but in my case `node['rvm']['gpg']['keyserver']` is set correctly

```
chef-shell -z
...
chef > node['rvm']['gpg']
 => {"keyserver"=>"hkp://keys.gnupg.net"} 
```

```
sudo chef-client
...
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.10.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc'!
...
STDERR: gpg: Signature made Mon Feb  2 16:09:00 2015 UTC using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
```

Running latest revision of chef-rvm (`bb9e174b64`), Chef 11.12.8 on Ubuntu 14.04.1.

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
