### ISSUE TITLE
GPG configuration is broken

### ISSUE THREAD

**Issue by sauliusgrigaitis** [sous-chefs/chef-rvm#307]
Trying to run `recipe[rvm::system]` without any attributes on clean Ubuntu 14.04.1 LTS with Chef 11.18.0:

```
[2015-02-05T14:05:27+00:00] INFO: Processing chef_gem[rvm] action install (rvm::default line 21)
/home/ubuntu/chef/site-cookbooks/rvm/libraries/rvm_chef_user_environment.rb:49: warning: class variable access from toplevel

================================================================================
Recipe Compile Error in /home/ubuntu/chef/site-cookbooks/rvm/recipes/system.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /home/ubuntu/chef/site-cookbooks/rvm/recipes/system_install.rb:33:in `from_file'
  /home/ubuntu/chef/site-cookbooks/rvm/recipes/system.rb:20:in `from_file'

Relevant File Content:
----------------------
/home/ubuntu/chef/site-cookbooks/rvm/recipes/system_install.rb:

 26:      group_name 'rvm'
 27:      gid        node['rvm']['group_id']
 28:      action     :nothing
 29:    end
 30:    g.run_action(:create)
 31:  end
 32:  
 33>> key_server = node['rvm']['gpg']['keyserver'] || "hkp://keys.gnupg.net"
 34:  home_dir = "#{node['rvm']['gpg']['homedir'] || '~'}/.gnupg"
 35:  
 36:  execute 'Adding gpg key' do
 37:    command "`which gpg2 || which gpg` --keyserver #{key_server} --homedir #{home_dir} --recv-keys #{node['rvm']['gpg_key']}"
 38:    only_if 'which gpg2 || which gpg'
 39:    not_if { node['rvm']['gpg_key'].empty? }
 40:  end
 41:  
 42:  rvm_installation("root")

[2015-02-05T14:05:28+00:00] ERROR: Running exception handlers
[2015-02-05T14:05:28+00:00] ERROR: Exception handlers complete
[2015-02-05T14:05:28+00:00] FATAL: Stacktrace dumped to /home/ubuntu/chef/chef-stacktrace.out
[2015-02-05T14:05:28+00:00] ERROR: undefined method `[]' for nil:NilClass
[2015-02-05T14:05:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Tried to set `node['rvm']['gpg']` to empty hash and bumped to new issue #306

**Comment by okeefm** [comment]
I have this same issue. My workaround was setting `node[:rvm][:gpg][:keyserver] = "hkp://keys.gnupg.net"`, which sounds similar.

**Comment by dharmarth** [comment]
Facing exact same issue with Ubuntu 14.04.1 & Chef-solo 12.0.0. Resetting `<node['rvm']['gpg']>` to `<{}>` also not helping.

**Comment by okeefm** [comment]
@dharmarth instead of setting `node['rvm']['gpg']` to `{}`, try the following line: `node[:rvm][:gpg][:keyserver] = "hkp://keys.gnupg.net"`.

**Comment by dharmarth** [comment]
@okeefm thanks for mentioning workaround again. It worked. 

I had a look at recipe and usage is `key_server = node['rvm']['gpg']['keyserver'] || "hkp://keys.gnupg.net"` so if `node['rvm']['gpg']` is empty it should fallback to `"hkp://keys.gnupg.net"`.

**Comment by okeefm** [comment]
One way to fix it would be something like `key_server = node['rvm']['gpg'] && node['rvm']['gpg'][keyserver'] || "hkp://keys.gnupg.net"`. A little hacky, but if `node['rvm']['gpg']` is nil, it won't even try to evaluate the second part and won't throw the exception.

**Comment by neurogenesis** [comment]
chef-sugar's ```deep_fetch``` is helpful for testing nested hashes, but unfortunately adds another dependency to the cookbook:

https://github.com/sethvargo/chef-sugar#node

(see examples for the use of deep_fetch)

**Comment by spuder** [comment]
I'm also running into this error. None of the suggested work arounds work for me. 

node[:rvm][:gpg][:keyserver] = "hkp://keys.gnupg.net"
node.default['rvm']['gpg']['keyserver'] = 'http://pgp.mit.edu'
node.default['rvm']['gpg']['keyserver'] = {}
```
       Recipe: rvm::default
         * chef_gem[rvm] action install (up to date)
       /tmp/kitchen/cookbooks/rvm/libraries/rvm_chef_user_environment.rb:49: warning: class variable access from toplevel

         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cookbooks/rvm/recipes/system.rb
         ================================================================================

         NoMethodError
         -------------
         undefined method `[]' for nil:NilClass

         Cookbook Trace:
         ---------------
           /tmp/kitchen/cookbooks/rvm/recipes/system_install.rb:33:in `from_file'
           /tmp/kitchen/cookbooks/rvm/recipes/system.rb:20:in `from_file'

         Relevant File Content:
         ----------------------
         /tmp/kitchen/cookbooks/rvm/recipes/system_install.rb:

          26:      group_name 'rvm'
          27:      gid        node['rvm']['group_id']
          28:      action     :nothing
          29:    end
          30:    g.run_action(:create)
          31:  end
          32:
          33>> key_server = node['rvm']['gpg']['keyserver'] || "hkp://keys.gnupg.net"
          34:  home_dir = "#{node['rvm']['gpg']['homedir'] || '~'}/.gnupg"
          35:

          37:    command "`which gpg2 || which gpg` --keyserver #{key_server} --homedir #{home_dir} --recv-keys #{node['rvm']['gpg_key']}"
          38:    only_if 'which gpg2 || which gpg'
          39:    not_if { node['rvm']['gpg_key'].empty? }
          40:  end
          41:
          42:  rvm_installation("root")
```

The only way I can get past this error is to revert back to an older cookbook version as suggested here
https://github.com/martinisoft/chef-rvm/issues/306#issuecomment-77992727

0.9.2 (dd58087e7399097a9b9df4e2e7235908aace2afd

Still not able to get this working because that cookbook has a different bug.

**Comment by neurogenesis** [comment]
I spent a few days struggling with this and I kept hitting issues with where the gpg key was being added vs. where it was being verified. When run from test kitchen, the user & HOME env variables are set, but when run from a cloud-init provisioned server, the user / HOME directory doesn't seem to be set (although chef-client is invoked as sudo and running with the privileges of root).

https://github.com/martinisoft/chef-rvm/blob/master/recipes/system_install.rb#L34

**NOTE**: system_install works fine so long as you're not using the 'upgrade' option as part of the node['rvm'] attributes.

What ends up happening is that the gpg key is added to `/.gnupg` (instead of `~/.gnupg` or `/root/.gnupg`). Verification during rvm install then uses a different path, so the verification fails.

On top of this, the gpg/gpg2 app itself was written poorly. When intentionally & successfully adding a new public gpg key the app exists with error conditions (results are sent to STDERR instead of STDOUT and app exists with non-zero exit code). This is to say that if you successfully import a key, the chef run will still fail because of a non-zero exit code. You can work around this with something like the following:

```
# NOTE: i'm installing the gpg key via import from a file resource...

gpg_bin = `which gpg2 || which gpg`
gpg_cmd = "#{gpg_cmd} --homedir #{home_dir} --import #{rvm_public_key}" +
    " || gpg2 --homedir #{home_dir} --list-public-keys | grep D39DC0E3"

ruby_version = node["rvm"]["default_ruby"]
include_recipe "rvm::system"
```

The logical OR (via `||`) allows the gpg import command to do its thing and exit with a non-zero exit code, but considers the entire command a success if the output of the `gpg --list-public-keys` contains the imported key. If both fail then something went wrong and the chef run should fail as a result.

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
