### ISSUE TITLE
Use name:ver instead. Error while installing.

### ISSUE THREAD

**Issue by pustserg** [sous-chefs/chef-rvm#310]
Just try install system wide rvm, and got the error

Recipe Compile Error in /home/deployer/chef-solo/cookbooks-2/rvm/recipes/system.rb
  ================================================================================

  Mixlib::ShellOut::ShellCommandFailed

---

  chef_gem[rvm](rvm::default line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
  ---- Begin output of /opt/chef/embedded/bin/gem install rvm -q --no-rdoc --no-ri -v ">= 1.11.3.6" ----
  STDOUT: 
  STDERR: ERROR:  Can't use --version w/ multiple gems. Use name:ver instead.
  ---- End output of /opt/chef/embedded/bin/gem install rvm -q --no-rdoc --no-ri -v ">= 1.11.3.6" ----
  Ran /opt/chef/embedded/bin/gem install rvm -q --no-rdoc --no-ri -v ">= 1.11.3.6" returned 1

  Cookbook Trace:

---

```
/home/deployer/chef-solo/cookbooks-2/rvm/recipes/default.rb:21:in `from_file'
/home/deployer/chef-solo/cookbooks-2/rvm/recipes/system_install.rb:20:in `from_file'
/home/deployer/chef-solo/cookbooks-2/rvm/recipes/system.rb:20:in `from_file'
```

  Relevant File Content:

---

  /home/deployer/chef-solo/cookbooks-2/rvm/recipes/default.rb:

   14:  # distributed under the License is distributed on an "AS IS" BASIS,
   15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   16:  # See the License for the specific language governing permissions and
   17:  # limitations under the License.
   18:  #
   19:  
   20:  # install rvm api gem during chef compile phase
   21>> chef_gem 'rvm' do
   22:    action :install
   23:    version '>= 1.11.3.6'
   24:  end
   25:  require 'rvm'
   26:  
   27:  create_rvm_shell_chef_wrapper
   28:  create_rvm_chef_user_environment
   29:  
   30:  class Chef::Resource

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
