### ISSUE TITLE
NoMethodError: undefined method `chomp' for nil:NilClass

### ISSUE THREAD

**Issue by jtmalinowski** [sous-chefs/chef-rvm#322]
Hi,
First of all - thanks for all the hard work you put into this.
I'm running chef-rvm (master) with Chef-Solo, with this node config (irrelevant parts omitted):

```
{
  "run_list": [
    "recipe[apt]",
    "recipe[git]",
    "recipe[rvm::user]",
  ],
  "rvm": {
    "version": "1.26.10",
    "gpg": {},
    "user_installs": [{
      "user": "app",
      "install_rubies": true,
      "default_ruby": "ruby-2.1.5",
      "rubies": ["ruby-2.1.5"]
    }]
  },
```

Stacktrace:

```
    /root/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_string_cache.rb:80:in `canonical_ruby_string'
    /root/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
    /root/chef-solo/cookbooks-2/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
    /root/chef-solo/cookbooks-2/rvm/providers/ruby.rb:26:in `load_current_resource'
```

In this line:
`result = stdout.read.split('\n').first.chomp`
`stdout.read` returns empty string and hance we get the error

The shell command which returns this empty string is:
`source /home/app/.rvm/scripts/rvm && rvm_ruby_string='ruby-2.1.5' && __rvm_ruby_string && echo $rvm_ruby_string`

There is no directory `/home/app/.rvm` at this point.

In one of issues you guys suggested that user might not be created at this point, but lack of the user is not the problem here, because I checked and the user is there.

Dunno if it's related but at first I misconfigured chef-rvm, and node['rvm']['user_installs'] was an empty array or nil - I can't quite remember right now - but there were no errors at the time.

**Comment by linc01n** [comment]
I have this problem also.

Seems the attribute structure changed.

When I use 

```json
"rvm": {
    "installs": {
    	"app": {
    		"action": "force",
    		"default_ruby": "ruby-2.1.5"
    	}
    },
    "rvmrc": {
      "rvm_autolibs_flag": "disabled"
    },
    "user_install_rubies": "true"
  }
```

Then it installs without problem.

**Comment by bpieck** [comment]
I think user installs is a bid messed uped. I changed to use the resources directly to avoid this error.

**Comment by jblaine** [comment]
It's not just user installs. I get the same error when using just a basic setup as follows (rvm cookbook version 0.9.2, latest released):

Attributes:

    default['rvm']['rubies'] = ['2.2.2', '2.1.6']

Recipe:

    include_recipe 'rvm::system'

Error:


```
  * rvm_ruby[2.2.2] action install[2015-05-19T12:39:44-04:00] INFO: Processing rvm_ruby[2.2.2] action install (rvm::system line 177)


    ================================================================================
    Error executing action `install` on resource 'rvm_ruby[2.2.2]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `chomp' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
    /var/chef/cache/cookbooks/rvm/providers/ruby.rb:26:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb

    177:           rvm_ruby ruby do
    178:             patch            ruby_patch
    179:             user             opts[:user]
    180:             rubygems_version ruby_rubygems_version
    181:           end
    182:         end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:177:in `block in install_rubies'

    rvm_ruby("2.2.2") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :rvm_ruby
      cookbook_name "rvm"
      recipe_name "system"
      ruby_string "2.2.2"
    end
```

**Comment by jblaine** [comment]
In our case, I just determined that the reported bug was surfacing due to curl failing to fetch https://get.rvm.io due to the certificate.

I worked around it (but it's totally a bug) by sticking `rvm-installer` (from http://rvm.io) on an internal web server, changing `default['rvm']['installer_url']` to point there, and running again.

**Comment by brauliobo** [comment]
+1 same here
@jblaine how to download `rvm-installer`

**Comment by jblaine** [comment]
@brauliobo curl -o ./rvm-installer https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer

**Comment by cheshire-cat** [comment]
Hi @brauliobo 
You can install rvm for single user with rvm.io installer like this:
```
package 'curl'

execute 'install gpg key' do
  user        'youruser'
  cwd         '/home/youruser'
  environment 'HOME' => '/home/youruser'
  command     'gpg --keyserver hkp://keys.gnupg.net'+\
              ' --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3'
  not_if      "gpg --list-keys | grep 'D39DC0E3'", user: 'youruser'
end

execute 'install rvm' do
  user        'youruser'
  cwd         '/home/youruser'
  environment 'HOME' => '/home/youruser'
  command     '\curl -sSL https://get.rvm.io | bash -s stable'
  not_if      'which rvm', user: 'youruser'
end
```

**Comment by scalp42** [comment]
@martinisoft any chance for a PR?

**Comment by martinisoft** [comment]
@scalp42 I don't see one linked to this issue, is there one that addresses the problem?

**Comment by vs-adm** [comment]
There is a dirty workaround for it. Add this resources to the recipe right before ruby install action

    execute 'gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3'
    execute 'curl -sSL https://get.rvm.io | bash -s stable'

**Comment by romanvbabenko** [comment]
+1 got the same error

**Comment by ephantom** [comment]
I got the same error for the setup below.  Works fine if I just try to install ruby-1.8.7-p374 by itself, but if I try installing the gem xml-simple I get the "undefined method `chomp' for nil:NilClass" error.

Here are the key parts of my cookbook recipe:

```
execute 'gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3'
execute 'curl -sSL https://get.rvm.io | bash -s stable'

node.default['rvm']['default_ruby'] = "ruby-1.8.7-p374"

# Note: tried both ways got the same error:
# node.default['rvm']['rubies'] = ["xml-simple"]
# and: 
    rvm_ruby("xml-simple") do
      action :install
    end

---------------

  * execute[gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3] action run
    - execute gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  * execute[curl -sSL https://get.rvm.io | bash -s stable] action run
    - execute curl -sSL https://get.rvm.io | bash -s stable
  * rvm_ruby[xml-simple] action install

    ================================================================================
    Error executing action `install` on resource 'rvm_ruby[xml-simple]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `chomp' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
    /var/chef/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
    /var/chef/cache/cookbooks/rvm/providers/ruby.rb:26:in `load_current_resource'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/status_voice/recipes/default.rb

     42:     rvm_ruby("xml-simple") do
     43:       action :install
     44:     end
     45:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/status_voice/recipes/default.rb:42:in `from_file'

    rvm_ruby("xml-simple") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :rvm_ruby
      cookbook_name "status_voice"
      recipe_name "default"
      ruby_string "xml-simple"
    end


Running handlers:
[2015-09-22T13:12:48-08:00] ERROR: Running exception handlers
```

**Comment by zl4bv** [comment]
I can replicate this issue right now, even though I've successfully used this cookbook with the same configuration in the past. The key difference between then and now is that https://get.rvm.io is currently refusing connections.

The `install_command` defined [here](https://github.com/martinisoft/chef-rvm/blob/v0.9.4/libraries/chef_rvm_recipe_helpers.rb#L73) exits with status code 0 even though the command didn't finish as expected - so the `execute` resource reports success.

```
         * execute[install system-wide RVM] action run[2016-09-07T06:50:53+00:00] INFO: Processing execute[install system-wide RVM] action run (rvm::system_install line 76)
       [2016-09-07T06:50:53+00:00] DEBUG: Resources for generic execute resource enabled on node include: [Chef::Resource::Execute]
       [2016-09-07T06:50:53+00:00] DEBUG: Resource for execute is Chef::Resource::Execute
       [2016-09-07T06:50:53+00:00] INFO: Processing execute[Guard resource] action run (dynamically defined)
       [2016-09-07T06:50:53+00:00] DEBUG: Providers for generic execute resource enabled on node include: [Chef::Provider::Execute]
       [2016-09-07T06:50:53+00:00] DEBUG: Provider for action run on resource execute[Guard resource] is Chef::Provider::Execute
       bash: /etc/profile.d/rvm.sh: No such file or directory
       [2016-09-07T06:50:53+00:00] DEBUG: Providers for generic execute resource enabled on node include: [Chef::Provider::Execute]
       [2016-09-07T06:50:53+00:00] DEBUG: Provider for action run on resource execute[install system-wide RVM] is Chef::Provider::Execute

           [execute]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                               Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to get.rvm.io port 443: Connection refused
       [2016-09-07T06:50:55+00:00] INFO: execute[install system-wide RVM] ran successfully
           - execute curl -L https://get.rvm.io | bash  -s -- --branch stable --version head
         * execute[upgrade system-wide RVM to none] action run[2016-09-07T06:50:55+00:00] INFO: Processing execute[upgrade system-wide RVM to none] action run (rvm::system_install line 115)
        (skipped due to not_if)
       [2016-09-07T06:50:55+00:00] DEBUG: Skipping execute[upgrade system-wide RVM to none] due to not_if ruby block
       Recipe: rvm::system
         * rvm_ruby[ruby-2.3] action install[2016-09-07T06:50:55+00:00] INFO: Processing rvm_ruby[ruby-2.3] action install (rvm::system line 177)
       [2016-09-07T06:50:55+00:00] DEBUG: Providers for generic rvm_ruby resource enabled on node include: [LWRP provider rvm_ruby from cookbook rvm]
       [2016-09-07T06:50:55+00:00] DEBUG: Provider for action install on resource rvm_ruby[ruby-2.3] is LWRP provider rvm_ruby from cookbook rvm
       [2016-09-07T06:50:55+00:00] DEBUG: Fetching canonical RVM string for: ruby-2.3 (system)


           ================================================================================
           Error executing action `install` on resource 'rvm_ruby[ruby-2.3]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `chomp' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
           /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
           /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
           /tmp/kitchen/cache/cookbooks/rvm/providers/ruby.rb:26:in `load_current_resource'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb

           177:           rvm_ruby ruby do
           178:             patch            ruby_patch
           179:             user             opts[:user]
           180:             rubygems_version ruby_rubygems_version
           181:           end
           182:         end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:177:in `block in install_rubies'

           rvm_ruby("ruby-2.3") do
             action :install
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :rvm_ruby
             cookbook_name "rvm"
             recipe_name "system"
             ruby_string "ruby-2.3"
           end

           Platform:
           ---------
           x86_64-linux
```

A potential solution is:

```ruby
install_command = "set -o pipefail; curl -L #{opts[:installer_url]} | bash #{opts[:script_flags]}"
```

**Comment by SandeepJoelFreshdesk** [comment]
> I can replicate this issue right now, even though I've successfully used this cookbook with the same configuration in the past. The key difference between then and now is that https://get.rvm.io is currently refusing connections.
> 
> The `install_command` defined [here](https://github.com/martinisoft/chef-rvm/blob/v0.9.4/libraries/chef_rvm_recipe_helpers.rb#L73) exits with status code 0 even though the command didn't finish as expected - so the `execute` resource reports success.
> 
> ```
>          * execute[install system-wide RVM] action run[2016-09-07T06:50:53+00:00] INFO: Processing execute[install system-wide RVM] action run (rvm::system_install line 76)
>        [2016-09-07T06:50:53+00:00] DEBUG: Resources for generic execute resource enabled on node include: [Chef::Resource::Execute]
>        [2016-09-07T06:50:53+00:00] DEBUG: Resource for execute is Chef::Resource::Execute
>        [2016-09-07T06:50:53+00:00] INFO: Processing execute[Guard resource] action run (dynamically defined)
>        [2016-09-07T06:50:53+00:00] DEBUG: Providers for generic execute resource enabled on node include: [Chef::Provider::Execute]
>        [2016-09-07T06:50:53+00:00] DEBUG: Provider for action run on resource execute[Guard resource] is Chef::Provider::Execute
>        bash: /etc/profile.d/rvm.sh: No such file or directory
>        [2016-09-07T06:50:53+00:00] DEBUG: Providers for generic execute resource enabled on node include: [Chef::Provider::Execute]
>        [2016-09-07T06:50:53+00:00] DEBUG: Provider for action run on resource execute[install system-wide RVM] is Chef::Provider::Execute
> 
>            [execute]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                                Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (7) Failed to connect to get.rvm.io port 443: Connection refused
>        [2016-09-07T06:50:55+00:00] INFO: execute[install system-wide RVM] ran successfully
>            - execute curl -L https://get.rvm.io | bash  -s -- --branch stable --version head
>          * execute[upgrade system-wide RVM to none] action run[2016-09-07T06:50:55+00:00] INFO: Processing execute[upgrade system-wide RVM to none] action run (rvm::system_install line 115)
>         (skipped due to not_if)
>        [2016-09-07T06:50:55+00:00] DEBUG: Skipping execute[upgrade system-wide RVM to none] due to not_if ruby block
>        Recipe: rvm::system
>          * rvm_ruby[ruby-2.3] action install[2016-09-07T06:50:55+00:00] INFO: Processing rvm_ruby[ruby-2.3] action install (rvm::system line 177)
>        [2016-09-07T06:50:55+00:00] DEBUG: Providers for generic rvm_ruby resource enabled on node include: [LWRP provider rvm_ruby from cookbook rvm]
>        [2016-09-07T06:50:55+00:00] DEBUG: Provider for action install on resource rvm_ruby[ruby-2.3] is LWRP provider rvm_ruby from cookbook rvm
>        [2016-09-07T06:50:55+00:00] DEBUG: Fetching canonical RVM string for: ruby-2.3 (system)
> 
> 
>            ================================================================================
>            Error executing action `install` on resource 'rvm_ruby[ruby-2.3]'
>            ================================================================================
> 
>            NoMethodError
>            -------------
>            undefined method `chomp' for nil:NilClass
> 
>            Cookbook Trace:
>            ---------------
>            /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:77:in `canonical_ruby_string'
>            /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:50:in `fetch'
>            /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_helpers.rb:55:in `normalize_ruby_string'
>            /tmp/kitchen/cache/cookbooks/rvm/providers/ruby.rb:26:in `load_current_resource'
>            /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
> 
>            Resource Declaration:
>            ---------------------
>            # In /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb
> 
>            177:           rvm_ruby ruby do
>            178:             patch            ruby_patch
>            179:             user             opts[:user]
>            180:             rubygems_version ruby_rubygems_version
>            181:           end
>            182:         end
> 
>            Compiled Resource:
>            ------------------
>            # Declared in /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:177:in `block in install_rubies'
> 
>            rvm_ruby("ruby-2.3") do
>              action :install
>              retries 0
>              retry_delay 2
>              default_guard_interpreter :default
>              declared_type :rvm_ruby
>              cookbook_name "rvm"
>              recipe_name "system"
>              ruby_string "ruby-2.3"
>            end
> 
>            Platform:
>            ---------
>            x86_64-linux
> ```
> A potential solution is:
> 
> ```ruby
> install_command = "set -o pipefail; curl -L #{opts[:installer_url]} | bash #{opts[:script_flags]}"
> ```

Can someone explain how to fix this issue ?

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
