### ISSUE TITLE
Net::HTTPServerException 403 Forbidden while executing rvm::system_install

### ISSUE THREAD

**Issue by joshi4** [sous-chefs/chef-rvm#340]
running on `Ubuntu 14.04.2 LTS` 
chef-client version is 11.16.4

```
Recipe: rvm::default
   * chef_gem[rvm] action install (up to date)
 Recipe: rvm::system_install
   * execute[Adding gpg key] action run
     - execute `which gpg2 || which gpg` --keyserver hkp://keys.gnupg.net --homedir /root/.gnupg --recv-keys D39DC0E3
   * rvm_installation[root] action install
   Recipe: <Dynamically Defined Resource>
     * template[/etc/rvmrc] action create

       ================================================================================
       Error executing action `create` on resource 'template[/etc/rvmrc]'
       ================================================================================

       Net::HTTPServerException
       ------------------------
       403 "Forbidden"

       Cookbook Trace:
       ---------------
       /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:95:in `write_rvmrc'
       /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:59:in `block in converge_rvmrc'
       /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:59:in `converge_rvmrc'
       /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:45:in `action_install'

       Compiled Resource:
       ------------------
       # Declared in

       template("/etc/rvmrc") do
         provider Chef::Provider::Template
         action "create"
         retries 0
         retry_delay 2
         guard_interpreter :default
         path "/etc/rvmrc"
         backup 5
         atomic_update true
         source "rvmrc.erb"
         cookbook "rvm"
         variables {:user=>"root", :rvm_path=>"/usr/local/rvm", :rvmrc_env=>{"rvm_gem_options"=>"--no-ri --no-rdoc"}}
         mode "0644"
         owner "root"
         group 0
       end


     ================================================================================
     Error executing action `install` on resource 'rvm_installation[root]'
     ================================================================================

     Net::HTTPServerException
     ------------------------
     template[/etc/rvmrc] (dynamically defined) had an error: Net::HTTPServerException: 403 "Forbidden"

     Cookbook Trace:
     ---------------
     /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:95:in `write_rvmrc'
     /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:59:in `block in converge_rvmrc'
     /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:59:in `converge_rvmrc'
     /var/chef/cache/cookbooks/rvm/libraries/provider_rvm_installation.rb:45:in `action_install'

     Resource Declaration:
     ---------------------
     # In /var/chef/cache/cookbooks/rvm/recipes/system_install.rb

      43: rvm_installation('root')

     Compiled Resource:
     ------------------
     # Declared in /var/chef/cache/cookbooks/rvm/recipes/system_install.rb:43:in `from_file'

     rvm_installation("root") do
       provider Chef::Provider::RvmInstallation
       action :install
       retries 0
       retry_delay 2
       guard_interpreter :default
       user "root"
       installer_url "https://get.rvm.io"
       installer_flags "stable"
       install_pkgs ["sed", "grep", "tar", "gzip", "bzip2", "bash", "curl", "git-core"]
       rvmrc_template_source "rvmrc.erb"
       rvmrc_template_cookbook "rvm"
       default_rvmrc_env {"rvm_gem_options"=>"--no-ri --no-rdoc"}
       rvmrc_env {"rvm_gem_options"=>"--no-ri --no-rdoc"}
       cookbook_name "rvm"
       recipe_name "system_install"
     end
```

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
