### ISSUE TITLE
OS X ProviderNotFound under chef 12

### ISSUE THREAD

**Issue by tomharvey** [sous-chefs/chef-rvm#353]
Chef 12 uses homebrew as default package manager and the suggested homebrew cookbook is no longer relevant.

When running this recipe I was seeing:

```
 ================================================================================
  Recipe Compile Error in /Users/thomasharvey/.chef/cache/cookbooks/rvm/recipes/user.rb
  ================================================================================

  Chef::Exceptions::ProviderNotFound
  ----------------------------------
  Cannot find a provider for package on mac_os_x version 10.11.3

  Cookbook Trace:
  ---------------
    /Users/thomasharvey/.chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:221:in `mac_with_no_homebrew'
    /Users/thomasharvey/.chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:42:in `install_pkg_prereqs'
    /Users/thomasharvey/.chef/cache/cookbooks/rvm/recipes/user_install.rb:22:in `from_file'
    /Users/thomasharvey/.chef/cache/cookbooks/rvm/recipes/user.rb:20:in `from_file'

  Relevant File Content:
  ----------------------
  /Users/thomasharvey/.chef/cache/cookbooks/rvm/libraries/chef_rvm_recipe_helpers.rb:

  214:          end
  215:        end
  216:  
  217:        private
  218:  
  219:        def mac_with_no_homebrew
  222:          %w{ mac_os_x mac_os_x_server }.include?(node['platform']) &&
  223:            Chef::Platform.find_provider_for_node(node, :package) !=
  224:            Chef::Provider::Package::Homebrew
  225:        end
  226:      end
  227:    end
  228:  end
  229:  
```

In line with suggestions on https://github.com/chef/chef/issues/3257 I changed my cookbook to use `Chef::Resource.resource_for_node(:service, node)` instead of `Chef::Platform.find_provider_for_node(node, :package)`

This now works on OSX and Chef 12.

I'll link to a pull request, but unclear on how to test for this - open to suggestions.

**Comment by tomharvey** [comment]
I'm using 0.9.4 version of the cookbook - looks like this has been changed in master already, no?

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
