### ISSUE TITLE
Deprecated Features

### ISSUE THREAD

**Issue by askmike1** [sous-chefs/chef-rvm#363]
```
Deprecated features used!
  method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 1 location:
    - /var/chef/cache/cookbooks/rvm/attributes/default.rb:65:in `from_file'
   See https://docs.chef.io/deprecations_attributes.html for further details.
  node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) at 1 location:
    - /var/chef/cache/cookbooks/rvm/attributes/default.rb:67:in `from_file'
   See https://docs.chef.io/deprecations_attributes.html for further details.
  chef_gem[rvm] chef_gem compile_time installation is deprecated. Please set `compile_time false` on the resource to use the new behavior, or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - /var/chef/cache/cookbooks/rvm/recipes/default.rb:21:in `from_file'
   See https://docs.chef.io/deprecations_chef_gem_compile_time.html for further details.

```

**Comment by maage** [comment]
There seems to be fix for 1st deprecation here:

https://github.com/apalmblad/chef-rvm/commit/727c92fabc0a60c24bef19860bd3bb44fdfe81a3

I've not tested, but seems to be right as similar structure is used in rvm/providers/ruby.rb

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
